# Generated by Django 4.0.6 on 2022-07-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_candidatesapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='diversityGroup',
            field=models.CharField(choices=[('Women', 'Women'), ('Black/African American', 'Black'), ('Hispanic/Latin', 'Latin'), ('Asian', 'Asian'), ('Veteran', 'Veteran'), ('Disabled', 'Disabled'), ('LGBTQIA+', 'Lgbtqia'), ('50+ Workforce', 'Workforce50')], default='Women', max_length=30),
        ),
    ]
